export const ROUTES = {
  home: "/",
  about: "/about",
  aboutDocuments: "/about/documents",
  aboutCertificates: "/about/documents/certificates",
  aboutPresentation: "/about/documents/presentation",
  services: "/services",
  experience: "/experience",
  agents: "/agents",
  agent: (id: string) => `/agents/${id}`,
  properties: "/properties",
  propertiesBuy: "/properties/buy",
  propertiesRent: "/properties/rent",
  propertiesLuxury: "/properties/luxury",
  property: (id: string) => `/properties/${id}`,
  favorites: "/favorites",
  contacts: "/contacts",
  privacy: "/privacy-policy",
  terms: "/terms",
  admin: "/admin",
  adminProperties: "/admin/properties",
  adminAgents: "/admin/agents",
  adminServices: "/admin/services",
  adminRequests: "/admin/requests",
  adminCrm: "/admin/crm",
  adminCertificates: "/admin/certificates",
  adminSettings: "/admin/settings",
} as const;
